services:
  backend:
    depends_on:
      - mongodb
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./backend:/workdir/app
      - /workdir/app/node_modules
    environment:
      - PORT=9000
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongodb
      - COINWATCH_API_KEY=your_coinwatch_api_key
    command: sh -c "npm ci && npm run start:dev"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/workdir/app
      - /workdir/app/node_modules
    environment:
      - VITE_API_SERVER_BASE_URL=http://backend:9000
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev --host"

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /data/db
    logging:
      driver: "none"
  
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb
      - ME_CONFIG_BASICAUTH=false
    logging:
      driver: "none"